### ISSUE TITLE
Failed to resolve dependencies. 

### ISSUE THREAD

**Issue by zhang-bo-lilly** [netreconlab/ParseCareKit#134]
I ran into an issue when trying to install both ParseCareKit and CareKit via SPM to a SwiftUI app in Xcode 13. The detailed information is as follows: 

First, I created the app using the Swift + SwiftUI template 
![image](https://user-images.githubusercontent.com/42588744/136713197-40396576-e442-45e8-bc0b-f619a47542fe.png)

Next, I installed ParseCareKit via SPM following the instructions in the README
![image](https://user-images.githubusercontent.com/42588744/136713249-2c8d48b4-742f-4656-acdc-2009bd060319.png)

And this is what Xcode looks like afterward
![image](https://user-images.githubusercontent.com/42588744/136713270-c785ef80-81cf-4176-bc7e-ea1874f79891.png)

Next, I tried to install CareKit and CareKitUI via SPM and planned to skip CareKitStore as it is included in ParseCareKit already 
![image](https://user-images.githubusercontent.com/42588744/136713324-8e3fe158-d33f-4f31-9b1d-eb5243316d8e.png)

However, Xcode shows the following message 
![image](https://user-images.githubusercontent.com/42588744/136713341-dcd938ac-a56b-4c05-ab53-4a17230f6f58.png)

If I chose add anyway, and then make the following choices
![image](https://user-images.githubusercontent.com/42588744/136713353-40efa54c-336b-4496-9423-ea79eacd2d88.png)

Then Xcode shows the error "Failed to resolve dependencies" 
![image](https://user-images.githubusercontent.com/42588744/136713386-f5c44213-3361-4408-9977-f478e27a8527.png)

Did I make any mistake along the way? Thanks.

**Comment by cbaker6** [comment]
CareKit doesn't have an official release, so when selecting CareKit, you need to select the commit the main branch is looked to which is currently, https://github.com/netreconlab/ParseCareKit/blob/9a39b5a613ea560b30fdf8b1fd05b241258799a3/Package.resolved#L9

**Comment by zhang-bo-lilly** [comment]
Thanks @cbaker6, that solves my problem.
