### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by advatar** [netreconlab/ParseCareKit#97]
I have hacked CareKit so it works on macOS and now I would like to be able to sync with macOS as well. One obstacle is WatchConnectivity not being available. Ideas about how to replace this dependency?

**Comment by cbaker6** [comment]
ParseCareKit doesn't have `WatchConnectivity` as a dependency

**Comment by advatar** [comment]
Right, but the example does here https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/main/OCKSample/AppDelegate.swift#L96

**Comment by cbaker6** [comment]
That's used in the sample app because the watchOS doesn't have a sign-in screen, so iOS provides it's session token to watchOS for easy login. It's not needed for the iOS app to function, so if you have it working on another OS, it isn't needed.

**Comment by cbaker6** [comment]
Closing as this has been answered.
